package com.yuil.game.entity.message;

public enum EntityMessageType {
	TEST,
	ADD_BTOBJECT,
	GET_ALL_BTOBJECT,
	ADD_BALL,
	REMOVE_BTOBJECT,
	UPDATE_BTOBJECT_MOTIONSTATE,
	CHANGE_AVANTAR_STATE,
	APPLY_FORCE,
	RUN_CMD,
	C2S_ADD_PLAYER,
	S2C_ADD_PLAYER,
	UPDATE_LINEAR_VELOCITY,
	C2S_ENQUIRE_BTOBJECT,
	S2C_ADD_OBSTACLE,
	C2S_UPDATE_BTOBJECT_MOTIONSTATE,
	DO_ACTION,
	MAKE_EXPLOSION,
	MOVE_DIRECTION,
	S2C_CREATE_VOLLEYBALL_COURT
}
